#!/usr/bin/env bash
# This script installs NginX on a server.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx reload

