#!/usr/bin/env bash
# Configures an Nginx server
apt-get update
apt-get -y upgrade
apt-get -y install nginx
service nginx start
echo "Holberton School" | tee /usr/share/nginx/html/index.html
echo "Holberton School" | tee /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     location /redirect_me {
           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
      }
}
" | tee /etc/nginx/sites-available/default
service nginx restart

