#!/usr/bin/env bash
# This script configures a new Ubuntu machine with NginX with a custom header.
apt-get -y update
apt-get -y install nginx

# Configure firewall
ufw allow 'Nginx HTTP'

# Create and configure text for said webpage
echo "Holberton School" | tee /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" | tee /var/www/html/404.html

sed -i '/server_name _/a error_page 404 /404.html; \nlocation = /404.html \n{\nroot /var/www/html/;\ninternal; \n}' /etc/nginx/sites-available/default

# Add requested header
sed -i "/as directory, then fall back to displaying a 404./a \\ \t \t add_header X-Served-By $hostname;\n" /etc/nginx/sites-available/default

service nginx restart
