#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive out of it.
pass="$1"
mysqldump --user=root --password="$pass" --all-databases > backup.sql
tar -zcvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
