#!/usr/bin/env bash
# This script prints a short story for each user.

IFS=":"
while read user pass uid gid uid_info home_dir com
do
	echo "The user $user is part of the $gid gang, lives in $home_dir and rides $com. $uid's place is protected by the passcode $pass, more info about the user here: $uid_info"

done < "/etc/passwd"

