#!/usr/bin/env bash
# This script prints "Holberon School" 10 times, printing "Hi" on the 9th iteration.
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Holberton School"
	((i++))
done

