#!/usr/bin/env bash
# This script displays "Holberton School" 10 times, exchanging the 4 and 8 iteration for fortune telling.

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i++))
done

