#!/usr/bin/env bash
# This script displays "Holberton School" 20 times, except on bad luck numbers.

i=1
while [ $i -le 20 ]
do
echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((i++))
done

